### PR TITLE
New harmony

### PR DESCRIPTION
**Pull request by kfrncs**
Add Whole-Tone, Diminished Scales, Modes of the Melodic Minor

### CODE REVIEW

**Comment by Qirky** [comment]
Can I ask why you removed the dots in `.lib`? Are you using Python 2?

**Comment by kfrncs** [comment]
No I’m not! I don’t know why, but that’s the only way I could get it
running from my fork instead of from the pip installation. Didn’t mean to
include it in the pull request. I’m pretty new to python and git

**Comment by kfrncs** [comment]
```
!newHarmony ~/gits/FoxDot/FoxDot> python __main__.py 
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
    from .lib import FoxDotCode, handle_stdin
ModuleNotFoundError: No module named '__main__.lib'; '__main__' is not a package
exit 1

```

**Comment by Qirky** [comment]
Ah to run it from the repo you need to make sure you are in the directory but run `python -m FoxDot` instead of `python __main__.py`. You can install it locally using `python setup.py install` which means you can run `python -m FoxDot` or just `FoxDot` anywhere.

**Comment by kfrncs** [comment]
And if I install locally, the Atom plugin should take the correct location from the path to use it?

Let me know if I need to change anything about the commits to allow you to just take the changes in Scale.py. That was my intention.

**Pull request closed without merging**
