### PR TITLE
Support for using the synthdefs from Sonic Pi

### PR DESCRIPTION
**Pull request by stevearc**
Hey! I don't know how you feel about this, but I added the ability to load and use the synthdefs created by Sam Aaron for Sonic Pi. He's made some really great synths and I found myself wanting to use them in FoxDot. They're all under the [MIT License](https://github.com/samaaron/sonic-pi/blob/master/LICENSE.md), and I'm not attaching them to the codebase, merely adding tools that can interact with them. So I think everything should be kosher.

I created a ruby script to pull the metadata about the synths from the sonic-pi repo directly. From there I saved that metadata to a json file which can be packaged and distributed with FoxDot. It can be used as so:
```python
from FoxDot.lib.Custom.SonicPi import LoadSonicPiSynths, pisynth
# This will download the .scsyndef files from github if not already present
LoadSonicPiSynths()
a1 >> pisynth.tb303(amp=.1, dur=2, attack=.1, cutoff=100)
```
I put it under the `lib.Custom` module because it feels like a 3rd party extension or plugin, and I wanted to keep it out of the way of the main FoxDot functionality. I added the synths under the namespace `pisynth` because some of the names conflict. I don't love it. Open to other ideas.

In the future if you want to grab newer synths from Sonic Pi, you can clone the repo and run the `generate_sonic_pi.py <path-to-repo>` command to update the json file.

Note that they aren't quite *perfect*. They have no input bus so the control fx don't work on them. And for some reason that I can't figure out they are significantly louder than the FoxDot synths.

### CODE REVIEW

**Comment by Psykopear** [comment]
I like what you did, but wouldn't it be more maintainable to have copies of the synths used by FoxDot inside the repo? I think this solution opens up to problems in the future, being so coupled to the sonic-pi repo.

That's my opinion, but i think that extracting the most interesting synths from there and adding them as custom .scd files would be easier to maintain in the future. 
That said, this part of the code could be used to extract the informations needed to write a single .scd file, but I would keep it as a utility script or a separate package, to avoid having runtime errors caused by changes in the sonic-pi repo for example.

What do you think?

**Comment by stevearc** [comment]
I thought the PR would be more likely to be accepted if it didn't commit any code or assets from another project. The only problem this could cause is if the sonic-pi repo is for some reason taken off github in the future. If you look at the download code, it's [pinned to a specific ref](https://github.com/Qirky/FoxDot/pull/64/commits/219ae4d77e663699a4e1dbb124d8e3149f97f358#diff-2ef4aab82e5e6456a19ebf3a37aa65e2R101) so new commits to sonic pi won't affect it.

My first thought was to just migrate the synths, but they're in compiled `.scsyndef`, generated by [clojure using the overtone library](https://github.com/samaaron/sonic-pi/blob/master/etc/synthdefs/designs/sonic_pi/synths/basic.clj). I could translate the clojure into scd format maybe, but that seemed like a rabbit hole I didn't want to go down.

I looked around but I couldn't find what might be changing the amp on the existing synths. I'll just add another hack to make the sonic pi synths quieter because I do agree, it would be nice to not blast people in the ears :)

**Comment by Qirky** [comment]
Wow that's awesome - so it's possible to load any .scsyndef file? My thought on the amplitude issue, we could add some sort of "balance" attribute to each SynthDef which is basically an amp modifier. So default SynthDefs are 1 and multiply the amp value by 1 but Sonic Pi synths are ~0.1 and multiply the amplitude by 0.1 before being sent to SC? I agree that maintenance-wise .scd files would be better but having the ability to load a .scsyndef file adds some flexibility to FoxDot. As it's in the "custom" directory (which exists for extensions that people can add) I think it's ok. Maybe making a new sub-package called "Extensions" which isn't imported by default and can be added at run time by the user?

**Comment by Psykopear** [comment]
Uh, i forgot sonic-pi is overtone based. 
Well then yep, it's probably just easier to be able to parse that directly.

I agree it could be placed in a module that can be loaded if needed.

**Comment by Psykopear** [comment]
@stevearc for the amp, see here for example

https://github.com/Qirky/FoxDot/blob/master/FoxDot/lib/SCLang/_SynthDefs.py#L48

They are manually adjusted when defined. I think synthdefs taken from outside sounds louder because of some limiter with gains applied by foxdot

**Comment by stevearc** [comment]
Yep, it's possible to load any compiled `scsyndef` file :)

Okay I moved it into an `Extensions` module and added a `balance` property that controls the amp. Let me know if that's what you had in mind

**Comment by Psykopear** [comment]
Looks good to me, let's wait for @Qirky to have a look at it

**Comment by Psykopear** [comment]
Nope wait I have a problem here. I took your branch, installed FoxDot in a virtualenv, moved to a different directory, and couldn't import

`from FoxDot.lib.Extensions.SonicPi import LoadSonicPiSynths, pisynth`

I then went to the site-packages and noticed that the Extensions folder was containing only the json file, thus the interpreter could not find Extensions (without the __init__.py).

To solve this you should add  ```'FoxDot.lib.Extensions',``` in the packages list in setup.py

**Comment by stevearc** [comment]
Oh good catch! Thanks! I'll fix that when I get home

**Comment by Qirky** [comment]
Thanks guys! I will have a play around with it this evening

**Pull request merged**
